name: Scheduled Re-Build Images

on:
  pull_request:
    branches:
    - development
  # workflow_dispatch:
  # schedule:
  # every night at 2am
  #  - cron: "0 2 * * *"

jobs:
#  prepare-matrix:
#    runs-on: ubuntu-latest
#    outputs:
#      matrix: ${{ steps.set-matrix.outputs.matrix }}
#    steps:
#      # split the branches and repos into a matrix
#      -
  re-build-images:
    strategy:
      fail-fast: false
      matrix:
        branch: ${{ fromJSON(vars.BRANCHES_FOR_REBUILD) }}
        repo: ${{ fromJSON("mlrun,ui") }}
    runs-on: ubuntu-latest
    steps:
      - name: Echo Branch
        run: echo ${{ matrix.branch }} ${{ matrix.repo }}
#      - name: Re-Build Image
#        with:
#          owner: mlrun
#          repo: mlrun
#          github_token: ${{ secrets.RELEASE_GITHUB_ACCESS_TOKEN }}
#          workflow_file_name: build.yaml
#          ref: ${{ matrix.branch }}
#          wait_interval: 60
#          client_payload: '{"skip_images": "models-gpu,tests", "build_from_cache": "false"}'