name: System Tests Enterprise

on:
  push:
    branches:
      - '.+-system-tests'

  schedule:

    # * is a special character in YAML so you have to quote this string
    # Run the system tests every 7 hours
    - cron:  '0 */7 * * *'

  workflow_dispatch:
    inputs:
      docker_registry:
        description: 'Docker registry to pull images from (default: ghcr.io/, use registry.hub.docker.com/ for docker hub)'
        required: true
        default: 'ghcr.io/'
      docker_repo:
        description: 'Docker repo to pull images from (default: mlrun)'
        required: true
        default: 'mlrun'
      test_code_from_action:
        description: 'Take tested code from action REF (default: false - take from upstream) (note that test code will be taken from the action REF anyways)'
        required: true
        default: 'false'
      ui_code_from_action:
        description: 'Take ui code from action branch in mlrun/ui (default: false - take from upstream)'
        required: true
        default: 'false'
      clean_resources_in_teardown:
        description: 'Clean resources created by test (like project) in each test teardown (default: true - perform clean)'
        required: true
        default: 'true'
      override_iguazio_version:
        description: 'Override the configured target system iguazio version (leave empty to resolve automatically by the mlrun version)'
        required: false

jobs:
  prepare-system-tests-enterprise-ci:
    # When increasing the timeout make sure it's not larger than the schedule cron interval
    timeout-minutes: 50
    name: Prepare System Tests Enterprise
    runs-on: ubuntu-latest

    # let's not run this on every fork, change to your fork when developing
    if: github.repository == 'mlrun/mlrun' || github.event_name == 'workflow_dispatch'

    steps:
    - uses: actions/checkout@v2

  run-system-tests-enterprise-ci:
    # When increasing the timeout make sure it's not larger than the schedule cron interval
    timeout-minutes: 360
    name: Run System Tests Enterprise
    runs-on: ubuntu-latest
    # requires prepare to finish before starting
    needs: [prepare-system-tests-enterprise-ci]
    strategy:
      max-parallel: 1
      matrix:
        test_component: [api,runtimes,feature_store,projects,model_monitoring,examples,demos,backward_compatibility]
    # let's not run this on every fork, change to your fork when developing
    # always is used so the jobs in the matrix will continue even if one of them failed
    # contains(join(needs.*.result, ','), 'success') verifies that the all the jobs in needs ran successfully
    if: always() && contains(join(needs.*.result, ','), 'success') && (github.repository == 'mlrun/mlrun' || github.event_name == 'workflow_dispatch')

    steps:
    - uses: actions/checkout@v2
    - name: fail
      if: matrix.test_component == 'api'
      run: exit 1